Repository camelot-os/sentry-kernel, pull requests merged in 2025-04, with the labels that each got.

#10 ci,macosx: fixing MacOS build, removing pip upgrade
  .github/workflows/macos.yml
Labels: bug

#11 tests: removing gtest definitively
  kernel/tests/meson.build
  subprojects/gtest.wrap
Labels: test

#13 build: adding Stef as UAPI code owner
  CODEOWNERS
Labels: build-system

#9 build,deps: moving to camelot-hosted project
  .github/workflows/gnulinux.yml
  .github/workflows/macos.yml
  .github/workflows/proof.yml
  CONTRIBUTING.md
  README.md
  doc/concepts/concepts/events.rst
  doc/concepts/sw_architecture/bsp.rst
  subprojects/cmsis.wrap
  subprojects/devicetree.wrap
  subprojects/kconfig.wrap
  subprojects/meson-svd.wrap
  uapi/README.md
  uapi/src/lib.rs
Labels: documentation, dependencies

#14 Feature/bump meson to 1.7.0
  .github/workflows/gnulinux.yml
  .github/workflows/macos.yml
  .github/workflows/proof.yml
  requirements.txt
  support/arch/asm-cortex-m/meson.build
  uapi/meson.build
Labels: build-system
